const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x));const load=(key,fallback)=>{try{const x=localStorage.getItem(key);return x?JSON.parse(x):clone(fallback)}catch{return clone(fallback)}};
let recipes=load('seres_recipes_v2',window.DEFAULT_RECIPES),settings=load('seres_settings_v1',{title:'세레스 요리 도감',subtitle:'세레스의 모든 요리를 한눈에 찾아보세요!',color:'#526c48',banner:'assets/banner.jpg',bannerPosition:'center',infoIcon:'📋',effectIcon:'✨',ingredientIcon:'🥕',tierIcon:'👑',effectHeadingIcon:'✨',searchIcon:'🔎',cursorStyle:'hand',font:'changwon'}),favorites=load('seres_favs_v1',[]),tier=0,effect='전체',favsOnly=false,selectedId=null;
// Attach packaged recipe images to existing browser-saved recipes, without changing user edits.
const packagedImageById=new Map((window.DEFAULT_RECIPES||[]).map(r=>[r.id,r.image]));
recipes.forEach(r=>{
  const packaged=packagedImageById.get(r.id);
  if(packaged && (!r.image || /^data:image\//i.test(r.image) || (r.image.startsWith('assets/recipes/') && r.image!==packaged))) r.image=packaged;
});
const defaultCategories=[{name:'전투',icon:'⚔️',keywords:'공격,치명타,전투,피해,데미지'},{name:'능력치',icon:'💪',keywords:'힘,민첩,지능,스탯,능력치'},{name:'채광',icon:'⛏️',keywords:'채광,광물,광석,곡괭이'},{name:'낚시',icon:'🎣',keywords:'낚시,물고기,어획'},{name:'채집',icon:'🍃',keywords:'채집,수확,농사'},{name:'생존',icon:'❤️',keywords:'체력,방어,회복,포만감,생명'},{name:'기타',icon:'⭐',keywords:''}];
let categoryDefs=load('seres_categories_v1',defaultCategories);
const categoryNames=()=>['전체',...categoryDefs.map(c=>c.name)];
function categoriesFor(r){if(Array.isArray(r.categories)&&r.categories.length)return r.categories;return [...new Set((r.effects||[]).map(category))]}
function renderCategoryChecks(selected=[]){$('#recipeCategoryChecks').innerHTML=categoryDefs.map(c=>`<label class="categoryCheck"><input type="checkbox" value="${esc(c.name)}" ${selected.includes(c.name)?'checked':''}> ${esc(c.icon)} ${esc(c.name)}</label>`).join('')}
function renderCategoryEditor(){$('#categoryEditor').innerHTML=categoryDefs.map((c,i)=>`<div class="categoryEditRow" data-category-index="${i}"><input class="catIcon" aria-label="아이콘" value="${esc(c.icon)}" placeholder="✨"><input class="catName" aria-label="카테고리 이름" value="${esc(c.name)}" placeholder="이름"><input class="catKeywords" aria-label="자동 분류 키워드" value="${esc(c.keywords||'')}" placeholder="키워드 (쉼표로 구분)"><button type="button" data-remove-category="${i}">삭제</button></div>`).join('')}
function readCategoryEditor(){return [...document.querySelectorAll('.categoryEditRow')].map(row=>({icon:row.querySelector('.catIcon').value.trim()||'✨',name:row.querySelector('.catName').value.trim(),keywords:row.querySelector('.catKeywords').value.trim()})).filter(c=>c.name)}
$('#addCategory').onclick=()=>{categoryDefs=readCategoryEditor();categoryDefs.push({name:'새 카테고리',icon:'✨',keywords:''});renderCategoryEditor()};
$('#categoryEditor').onclick=e=>{const b=e.target.closest('[data-remove-category]');if(!b)return;categoryDefs=readCategoryEditor();categoryDefs.splice(Number(b.dataset.removeCategory),1);renderCategoryEditor()};
$('#saveCategories').onclick=async()=>{const next=readCategoryEditor();if(new Set(next.map(c=>c.name)).size!==next.length){alert('카테고리 이름은 중복될 수 없어요.');return}if(next.some(c=>c.name==='전체')){alert('전체는 예약된 이름이에요.');return}categoryDefs=next;localStorage.setItem('seres_categories_v1',JSON.stringify(categoryDefs));if(!categoryNames().includes(effect))effect='전체';renderCategoryChecks(recipes.find(r=>r.id===selectedId)?.categories||[]);try{await SeresCloud.saveSetting('categories',categoryDefs);render();alert('카테고리 설정이 전체 방문자에게 저장됐어요.')}catch(err){alert('서버 저장 실패: '+err.message)}};
function category(text){const s=String(text).toLowerCase();for(const c of categoryDefs){if(c.name==='기타')continue;if((c.keywords||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean).some(k=>s.includes(k)))return c.name}return categoryDefs.some(c=>c.name==='기타')?'기타':(categoryDefs[0]?.name||'전체')}
function store(){try{localStorage.setItem('seres_recipes_v2',JSON.stringify(recipes));return true}catch(err){alert('브라우저 저장 공간이 부족합니다. 이미지 크기를 줄이거나 JSON을 내보내 보관해 주세요.');return false}}function saveFav(){localStorage.setItem('seres_favs_v1',JSON.stringify(favorites))}
function applySettings(){applySiteFont();document.documentElement.dataset.cursorStyle=settings.cursorStyle||'hand';document.documentElement.style.setProperty('--green',settings.color);$('.hero').style.backgroundImage=`linear-gradient(0deg,#1e1a1370,#1e1a1340),url("${String(settings.banner).replace(/["\\]/g,'')}")`;$('.hero h1').textContent=settings.title;$('.hero p').textContent=settings.subtitle;document.title=settings.title;$('.hero').style.backgroundPosition=settings.bannerPosition||'center';$('#tierHeadingIcon').textContent=settings.tierIcon||'👑';$('#effectHeadingIcon').textContent=settings.effectHeadingIcon||'✨';$('.searchIcon').textContent=settings.searchIcon||'🔎'}
function renderFilters(){$('#tierChips').innerHTML=[0,...Array.from({length:10},(_,i)=>i+1)].map(t=>`<button class="chip ${tier===t?'active':''}" data-tier="${t}">${t?t+'티어':'전체'}</button>`).join('');$('#effectChips').innerHTML=categoryNames().map(c=>`<button class="chip ${effect===c?'active':''}" data-effect="${c}">${esc(c==='전체'?'🌿':(categoryDefs.find(x=>x.name===c)?.icon||'✨'))} ${c}</button>`).join('')}
function matches(r){const q=$('#search').value.trim().toLowerCase();const text=[r.name,r.description,...r.effects,...r.ingredients].join(' ').toLowerCase();return(!tier||Number(r.tier)===tier)&&(effect==='전체'||categoriesFor(r).includes(effect))&&(!q||text.includes(q))&&(!favsOnly||favorites.includes(r.id))}
function render(){renderFilters();let items=recipes.filter(matches);let sort=$('#sort').value;items.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'ko'):sort==='level'?a.level-b.level:sort==='duration'?b.duration-a.duration:a.tier-b.tier||a.name.localeCompare(b.name,'ko'));$('#heading').textContent=favsOnly?'즐겨찾기 요리':tier?`${tier}티어 요리 도감`:'전체 요리 도감';$('#count').textContent=`총 ${items.length}개의 요리`;$('#cards').innerHTML=items.map(r=>`<article class="foodCard" data-id="${esc(r.id)}" tabindex="0" role="button" aria-label="${esc(r.name)} 상세보기"><div class="foodVisual"><span class="tierBadge tier-${Number(r.tier)}">${Number(r.tier)}티어</span>${r.image?`<img src="${esc(r.image)}" alt="${esc(r.name)}" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'emoji',textContent:'🍲'}))">`:`<span class="emoji">${esc(r.emoji||'🍲')}</span>`}</div><div class="foodBody"><h3>${esc(r.name)}</h3>${r.effects.slice(0,2).map(e=>`<div class="effectLine">✨ ${esc(e)}</div>`).join('')}<div class="foodFoot"><span class="foodDuration"><span class="timeIcon">⏱️</span>${esc(r.durationText||`${Number(r.duration)}분`)}</span><button class="heart ${favorites.includes(r.id)?'on':''}" data-fav="${esc(r.id)}" aria-label="즐겨찾기"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 20.4C10.2 19.1 3.1 14.2 3.1 8.9c0-2.7 1.9-4.6 4.4-4.6 1.9 0 3.3 1.1 4.5 2.7 1.2-1.6 2.6-2.7 4.5-2.7 2.5 0 4.4 1.9 4.4 4.6 0 5.3-7.1 10.2-8.9 11.5Z"/></svg></button></div></div></article>`).join('');$('#empty').hidden=items.length>0}
function detail(id){const r=recipes.find(x=>x.id===id);if(!r)return;$('#detailContent').innerHTML=`<button class="detailClose" id="detailClose" aria-label="닫기">✕</button><div class="detailTop"><div class="detailImage">${r.image?`<img src="${esc(r.image)}" alt="" onerror="this.style.display='none';this.parentElement.classList.add('imageUnavailable')">`:esc(r.emoji||'🍲')}</div><div><span class="tierBadge tier-${Number(r.tier)}" style="position:static;display:inline-block">${r.tier}티어</span><h2>${esc(r.name)}</h2><p>${esc(r.description||'')}</p><div class="detailTags">${categoriesFor(r).map(c=>`<span>${esc(c)}</span>`).join('')}</div></div></div><section class="detailSection"><h3>${esc(settings.infoIcon||'📋')} 기본 정보</h3><div class="inside">요리 티어　${r.tier}티어<br>요구 레벨　Lv.${r.level}<br>지속 시간　${esc(r.durationText||`${r.duration}분`)}${r.vitality!=null?`<br>활력 소모량　${esc(r.vitality)}`:""}${r.successExp!=null?`<br>성공 경험치　${esc(r.successExp)}`:""}</div></section><section class="detailSection"><h3>${esc(settings.effectIcon||'✨')} 요리 효과</h3><div class="inside">${r.effects.length?r.effects.map(e=>'• '+esc(e)).join('<br>'):'등록된 효과 없음'}</div></section><section class="detailSection"><h3>${esc(settings.ingredientIcon||'🥕')} 필요 재료</h3><div class="inside">${r.ingredients.length?r.ingredients.map(e=>'• '+esc(e)).join('<br>'):'등록된 재료 없음'}</div></section>`;$('#detailDialog').showModal()}
$('#cards').addEventListener('click',e=>{const fav=e.target.closest('[data-fav]');if(fav){const id=fav.dataset.fav;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];saveFav();render();return}const card=e.target.closest('[data-id]');if(card)detail(card.dataset.id)});$('#cards').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('article'))detail(e.target.dataset.id)});
$('#detailContent').addEventListener('click',e=>{if(e.target.closest('#detailClose'))$('#detailDialog').close()});$('#detailDialog').addEventListener('click',e=>{if(e.target===$('#detailDialog'))e.target.close()});$('#tierChips').addEventListener('click',e=>{const b=e.target.closest('[data-tier]');if(b){tier=Number(b.dataset.tier);render()}});$('#effectChips').addEventListener('click',e=>{const b=e.target.closest('[data-effect]');if(b){effect=b.dataset.effect;render()}});$('#search').addEventListener('input',render);$('#searchBtn').onclick=render;$('#sort').onchange=()=>{syncPrettySort();render()};
function syncPrettySort(){const select=$('#sort');$('#sortText').textContent=select.selectedOptions[0].textContent;document.querySelectorAll('[data-sort]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.sort===select.value)))}
function closePrettySort(){ $('#sortMenu').hidden=true;$('#sortToggle').setAttribute('aria-expanded','false') }
$('#sortToggle').onclick=()=>{const menu=$('#sortMenu');menu.hidden=!menu.hidden;$('#sortToggle').setAttribute('aria-expanded',String(!menu.hidden))};
$('#sortMenu').onclick=e=>{const option=e.target.closest('[data-sort]');if(!option)return;$('#sort').value=option.dataset.sort;syncPrettySort();closePrettySort();render()};
document.addEventListener('click',e=>{if(!e.target.closest('#prettySort'))closePrettySort()});
$('#sortToggle').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();$('#sortMenu').hidden=false;$('#sortMenu button').focus()}if(e.key==='Escape')closePrettySort()});
$('#sortMenu').addEventListener('keydown',e=>{if(e.key==='Escape'){closePrettySort();$('#sortToggle').focus()}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const buttons=[...$('#sortMenu').querySelectorAll('button')];buttons[(buttons.indexOf(document.activeElement)+(e.key==='ArrowDown'?1:buttons.length-1))%buttons.length].focus()}});
syncPrettySort();$('#resetFilters').onclick=()=>{tier=0;effect='전체';favsOnly=false;$('#search').value='';render()};function goHome(e){if(e)e.preventDefault();tier=0;effect='전체';favsOnly=false;$('#search').value='';$('#sort').value='tier';syncPrettySort();render();window.scrollTo({top:0,behavior:'smooth'})}
function goCatalog(e){if(e)e.preventDefault();tier=0;effect='전체';favsOnly=false;$('#search').value='';render();$('#catalog').scrollIntoView({behavior:'smooth'})}
$('#brandHome').addEventListener('click',goHome);

$('#catalogNav').addEventListener('click',goCatalog);
$('#favNav').onclick=()=>{favsOnly=true;tier=0;effect='전체';$('#search').value='';render();$('#catalog').scrollIntoView({behavior:'smooth'})};
const form=$('#recipeForm');function edit(id){selectedId=id;const r=recipes.find(x=>x.id===id);if(!r)return;$('#recipeId').value=r.id;for(const key of ['name','tier','level','image','description'])form.elements[key].value=r[key]??'';form.elements.duration.value=r.durationText||`${Number(r.duration)||0}분`;form.elements.effects.value=r.effects.join('\n');form.elements.ingredients.value=r.ingredients.join('\n');renderCategoryChecks(r.categories||[]);updateImagePreview(r.image);$('#saveMessage').textContent='';renderAdminList()}
function renderAdminList(){let q=$('#adminSearch').value.toLowerCase();$('#adminRecipes').innerHTML=recipes.filter(r=>r.name.toLowerCase().includes(q)).map(r=>`<button class="adminItem ${r.id===selectedId?'selected':''}" data-edit="${esc(r.id)}">${esc(r.name)} · ${r.tier}티어</button>`).join('')}
function newRecipe(){const id='recipe-'+Date.now();recipes.push({id,name:'새 요리',tier:1,level:1,duration:10,durationText:'10분',image:'',description:'',effects:[],ingredients:[],emoji:'🍲'});render();edit(id)}
$('#adminOpen').onclick=async()=>{if(!await SeresCloud.requireAdmin())return;renderCategoryEditor();renderAdminList();if(recipes.length)edit(selectedId&&recipes.some(r=>r.id===selectedId)?selectedId:recipes[0].id);$('#settingTitle').value=settings.title;$('#settingSubtitle').value=settings.subtitle;$('#settingColor').value=settings.color;$('#settingBanner').value=settings.banner;for(const [field,key] of Object.entries({settingBannerPosition:'bannerPosition',settingInfoIcon:'infoIcon',settingEffectIcon:'effectIcon',settingIngredientIcon:'ingredientIcon',settingTierIcon:'tierIcon',settingEffectHeadingIcon:'effectHeadingIcon',settingSearchIcon:'searchIcon',settingCursorStyle:'cursorStyle'}))$('#'+field).value=settings[key]||'';$('#settingFont').value=settings.font||'changwon';$('#customFontStatus').textContent=customFontName?'저장된 글꼴: '+customFontName:'업로드한 글꼴은 이 브라우저에 저장됩니다.';$('#adminDialog').showModal();SeresCloud.addSeedButton()};$('#adminClose').onclick=()=>$('#adminDialog').close();$('#addRecipe').onclick=newRecipe;$('#adminRecipes').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)edit(b.dataset.edit)};$('#adminSearch').oninput=renderAdminList;
form.onsubmit=async e=>{e.preventDefault();let r=recipes.find(x=>x.id===selectedId);if(!r)return;for(const key of ['name','image','description'])r[key]=form.elements[key].value.trim();const durationValue=form.elements.duration.value.trim();r.durationText=durationValue;const timeMatch=durationValue.match(/(\d+)\s*분\s*(\d+)\s*초/);const minuteMatch=durationValue.match(/(\d+(?:\.\d+)?)\s*분/);r.duration=timeMatch?(Number(timeMatch[1])+Number(timeMatch[2])/60):minuteMatch?Number(minuteMatch[1]):Number(durationValue)||0;for(const key of ['tier','level'])r[key]=Number(form.elements[key].value);r.effects=form.elements.effects.value.split('\n').map(s=>s.trim()).filter(Boolean);r.ingredients=form.elements.ingredients.value.split('\n').map(s=>s.trim()).filter(Boolean);r.categories=[...$('#recipeCategoryChecks').querySelectorAll('input:checked')].map(x=>x.value);try{await SeresCloud.saveRecipe(r);store();render();renderAdminList();$('#saveMessage').textContent='Supabase에 저장 완료! 방문자에게도 반영돼요.'}catch(err){$('#saveMessage').textContent='저장 실패: '+err.message;alert('서버 저장 실패: '+err.message)}};$('#deleteRecipe').onclick=async()=>{if(!selectedId||!confirm('선택한 요리를 삭제할까요?'))return;try{await SeresCloud.deleteRecipe(selectedId);recipes=recipes.filter(r=>r.id!==selectedId);selectedId=null;store();render();renderAdminList();form.reset()}catch(err){alert('삭제 실패: '+err.message)}};
function fileToData(file,cb){if(!file)return;const reader=new FileReader();reader.onload=()=>cb(String(reader.result));reader.readAsDataURL(file)}function loadImageSource(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('이미지 데이터를 열 수 없습니다. PNG, JPG 또는 WEBP 파일을 다시 선택해 주세요.'));img.src=src})}
async function compactRecipeImage(file){if(!file||!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type))throw Error('PNG, JPG, WEBP 또는 GIF 이미지를 선택해 주세요.');if(file.size>15*1024*1024)throw Error('15MB 이하 이미지를 선택해 주세요.');const raw=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('파일을 읽을 수 없습니다.'));reader.readAsDataURL(file)});const img=await loadImageSource(raw);const ratio=Math.min(1,512/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(img.naturalHeight*ratio));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const result=canvas.toDataURL('image/png');await loadImageSource(result);return result}
async function updateImagePreview(src){const img=$('#imagePreview'),status=$('#imageStatus');img.hidden=true;img.removeAttribute('src');if(!src){status.textContent='이미지 없음';return}try{await loadImageSource(src);img.src=src;img.hidden=false;status.textContent='이미지 미리보기'}catch{status.textContent='이미지가 손상되었거나 경로를 찾을 수 없어요. 다시 업로드해 주세요.'}}
// Bundled Korean filenames are used directly: no Base64 conversion, no canvas decoding.
const packagedImagePaths=new Set((window.DEFAULT_RECIPES||[]).map(r=>r.image).filter(v=>typeof v==='string'&&v.startsWith('assets/recipes/')));
$('#imageUpload').onchange=async e=>{
  const file=e.target.files?.[0];if(!file)return;
  const status=$('#imageStatus');
  try{
    if(!/\.(png|jpe?g|webp|gif)$/i.test(file.name))throw Error('PNG, JPG, WEBP 또는 GIF 파일만 선택해 주세요.');
    const path='assets/recipes/'+file.name;
    if(packagedImagePaths.has(path)){
      form.elements.image.value=path;
      await updateImagePreview(path);
      status.textContent='등록 완료: '+file.name+' (사이트에 포함된 이미지)';
    }else{
      // For new images, retain the original data without re-encoding on canvas.
      if(file.size>3*1024*1024)throw Error('새 이미지는 3MB 이하로 사용해 주세요. 배포용은 assets/recipes 폴더에 추가하는 것이 좋아요.');
      const raw=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('이미지 파일을 읽을 수 없어요.'));reader.readAsDataURL(file)});
      await loadImageSource(raw);
      form.elements.image.value=raw;
      await updateImagePreview(raw);
      status.textContent='이미지 준비 완료: '+file.name+' (브라우저 임시 저장, 저장하기를 눌러주세요)';
    }
  }catch(err){status.textContent='업로드 실패: '+err.message+' / 기존 106개 음식 이미지는 업로드 없이 이미 연결되어 있어요.';}
  e.target.value='';
};
$('#clearRecipeImage').onclick=()=>{form.elements.image.value='';updateImagePreview('')};
form.elements.image.addEventListener('change',()=>updateImagePreview(form.elements.image.value.trim()));
$('#bannerUpload').onchange=e=>fileToData(e.target.files[0],data=>{$('#settingBanner').value=data;alert('배너가 입력됐어요. 설정 저장을 눌러주세요.')});
function download(name,content,type='application/json'){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#exportJson').onclick=()=>download('recipes.json',JSON.stringify(recipes,null,2));$('#importJson').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data)||!data.every(r=>typeof r.name==='string'&&Array.isArray(r.effects)&&Array.isArray(r.ingredients)))throw Error('요리 데이터 형식이 올바르지 않습니다.');recipes=data.map((r,i)=>{const rawDuration=String(r.duration??'');const mm=rawDuration.match(/(\d+)분\s*(\d+)초/);const dur=mm?(Number(mm[1])*60+Number(mm[2]))/60:Number(r.duration)||0;return {...r,id:String(r.id||'import-'+i),tier:Number(r.tier)||1,level:Number(r.level??r.requiredLevel)||0,duration:dur,durationText:r.durationText||(mm?rawDuration:undefined),ingredients:r.ingredients.map(x=>typeof x==='string'?x:`${x.name} x${x.amount}`)};});await SeresCloud.saveAllRecipes(recipes);store();selectedId=null;render();renderAdminList();if(recipes.length)edit(recipes[0].id);alert('Supabase로 불러오기 완료!')}catch(err){alert('불러오기 실패: '+err.message)}e.target.value=''};
$('#exportSite').onclick=async()=>{if(!confirm('브라우저에 저장한 요리 데이터를 초기화할까요?'))return;try{await SeresCloud.replaceAllRecipes(clone(window.DEFAULT_RECIPES));recipes=clone(window.DEFAULT_RECIPES);store();selectedId=null;render();renderAdminList();if(recipes.length)edit(recipes[0].id)}catch(err){alert('초기화 실패: '+err.message)}};
$('#saveSettings').onclick=async()=>{settings={title:$('#settingTitle').value.trim()||'세레스 요리 도감',subtitle:$('#settingSubtitle').value.trim(),color:$('#settingColor').value,banner:$('#settingBanner').value.trim()||'assets/banner.jpg',bannerPosition:$('#settingBannerPosition').value,infoIcon:$('#settingInfoIcon').value.trim()||'📋',effectIcon:$('#settingEffectIcon').value.trim()||'✨',ingredientIcon:$('#settingIngredientIcon').value.trim()||'🥕',tierIcon:$('#settingTierIcon').value.trim()||'👑',effectHeadingIcon:$('#settingEffectHeadingIcon').value.trim()||'✨',searchIcon:$('#settingSearchIcon').value.trim()||'🔎',cursorStyle:$('#settingCursorStyle').value||'hand',font:$('#settingFont').value||'changwon'};try{await SeresCloud.saveSetting('general',settings);localStorage.setItem('seres_settings_v1',JSON.stringify(settings));applySettings();alert('사이트 설정이 Supabase에 저장됐어요.')}catch{alert('브라우저 저장 공간이 부족합니다. 이미지 파일을 압축하거나 파일 경로를 사용해 주세요.')}};
// Font upload stored separately in IndexedDB (localStorage cannot safely hold large TTF files).
let customFontURL=null,customFontName='';
function fontDatabase(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('이 브라우저는 글꼴 저장을 지원하지 않습니다.'));const req=indexedDB.open('seres_font_storage',1);req.onupgradeneeded=()=>req.result.createObjectStore('fonts');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function saveCustomFont(file){const db=await fontDatabase();await new Promise((resolve,reject)=>{const tx=db.transaction('fonts','readwrite');tx.objectStore('fonts').put({blob:file,name:file.name},'custom');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();await loadCustomFont()}
async function loadCustomFont(){try{const db=await fontDatabase();const value=await new Promise((resolve,reject)=>{const tx=db.transaction('fonts','readonly');const req=tx.objectStore('fonts').get('custom');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();if(!value)return;if(customFontURL)URL.revokeObjectURL(customFontURL);customFontURL=URL.createObjectURL(value.blob);customFontName=value.name;const face=new FontFace('SeresCustomFont',`url("${customFontURL}")`);await face.load();document.fonts.add(face);applySiteFont()}catch(e){console.warn('사용자 글꼴을 불러오지 못했습니다:',e)}}
function applySiteFont(){const fonts={changwon:'ChangwonDangamRound',sangsang:'LocusSangsang',dongdong:'CafeDongdong',coco:'Cocochoitoon',basic:'Malgun Gothic',custom:customFontURL?'SeresCustomFont':'LocusSangsang'};document.documentElement.style.setProperty('--site-font',`'${fonts[settings.font||'changwon']||fonts.changwon}'`)}
$('#customFontUpload').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;if(!/\.(ttf|otf|woff2?)$/i.test(file.name)){alert('TTF, OTF, WOFF 또는 WOFF2 파일만 선택해 주세요.');return}if(file.size>20*1024*1024){alert('20MB 이하 글꼴을 선택해 주세요.');return}try{await saveCustomFont(file);$('#settingFont').value='custom';$('#customFontStatus').textContent='저장된 글꼴: '+file.name+' (설정 저장을 눌러 적용)'}catch(err){alert('글꼴 저장 실패: '+err.message)}};
// Apply the bundled font once, even if an older browser setting selected an unavailable font.
if(!localStorage.getItem('seres_changwon_font_migrated_v1')){
  settings.font='changwon';
  try{localStorage.setItem('seres_settings_v1',JSON.stringify(settings));localStorage.setItem('seres_changwon_font_migrated_v1','1')}catch{}
}
// JSON 파일을 배포할 경우 기본 데이터로 읽을 수 있도록 지원
async function init(){try{const cloud=await SeresCloud.loadPublic();if(cloud.recipes.length){recipes=cloud.recipes}else{recipes=clone(window.DEFAULT_RECIPES)}if(cloud.settings.general)settings=cloud.settings.general;if(cloud.settings.categories)categoryDefs=cloud.settings.categories;}catch(err){console.warn('Supabase 연결 실패, 내장 기본 자료를 표시합니다:',err);recipes=clone(window.DEFAULT_RECIPES)}await loadCustomFont();applySettings();render();SeresCloud.showStatus()}for(let i=1;i<=10;i++)$('#editTier').insertAdjacentHTML('beforeend',`<option value="${i}">${i}티어</option>`);init();
